package com.example.smarttrade.util

const val REQUEST_TOKEN = "requestToken"

const val SMART_TRADE_PREFERENCE = "smartTradePreference"

// Pending Intent request code
const val START_UPDATING_POSITION_REQUEST_CODE = 1
const val CANCEL_UPDATING_POSITION_REQUEST_CODE = 2
const val USER_LOGGED_OFF_REQUEST_CODE = 3
// intent identifier
const val STOP_UPDATING_POSITION_BROADCAST_INTENT_IDENTIFIER = "CANCEL_BROADCAST_INTENT_IDENTIFIER"
const val START_UPDATING_POSITION_BROADCAST_INTENT_IDENTIFIER = "START_BROADCAST_INTENT_IDENTIFIER"
const val SET_USER_LOGGED_OFF_BROADCAST_INTENT_IDENTIFIER = "SET_USER_LOGGED_OFF_BROADCAST_INTENT_IDENTIFIER"